INSERT INTO sede(id,nombre,img) VALUES(100,"SAN BERNARDO","/sede/sede_sanbernardo.jpg");
INSERT INTO sede(id,nombre,img) VALUES(200,"ANTONIO VARAS","/sede/a_varas.jpg");
INSERT INTO sede(id,nombre,img) VALUES(300,"ALAMEDA","/sede/sede_alameda.jpg");
INSERT INTO sede(id,nombre,img) VALUES(400,"CAMPUS ARAUCO","/sede/sede_arauco.jpg");
INSERT INTO sede(id,nombre,img) VALUES(500,"MAIPU","/sede/sede_maipu.jpg");
INSERT INTO sede(id,nombre,img) VALUES(600,"MELIPILLA","/sede/sede_melipilla.jpg");
INSERT INTO sede(id,nombre,img) VALUES(700,"PADRE ALONSO DE OVALLE","/sede/sede_padre_alonso.jpg");
INSERT INTO sede(id,nombre,img) VALUES(800,"PLAZA NORTE","/sede/sede_plazanorte.jpg");
INSERT INTO sede(id,nombre,img) VALUES(900,"PLAZA OESTE","/sede/sede_plazaoeste.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1000,"PUENTE ALTO","/sede/sede_puentealto.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1100,"SAN ANDRÉS DE CONCEPCIÓN","/sede/sede_sanandres.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1200,"SAN CARLOS DE APOQUINDO","/sede/sede_sancarlos.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1300,"SAN JOAQUIN","/sede/sede_sanjoaquin.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1400,"VALPARAISO","/sede/sede_valparaiso.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1500,"PLAZA VESPUCIO","/sede/sede_vespucio.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1600,"VIÑA DEL MAR","/sede/sede_vina.jpg");
INSERT INTO sede(id,nombre,img) VALUES(1800,'CAMPUS VILLARICA','/sede/sede_villarica.jpg');
INSERT INTO sede(id,nombre,img) VALUES(1900,'CASA CENTRAL','/sede/sede_casa_central.jpg');
INSERT INTO sede(id,nombre,img) VALUES(2000,'PUERTO MONTT','/sede/sede_puerto_montt.jpg');
INSERT INTO sede(id,nombre,img) VALUES(2100,'EDUCACIÓN CONTINUA','/sede/educacion_continua.jpg');
