INSERT INTO sede(id,nombre,img,activo) VALUES(100,"SAN BERNARDO","/sede/sede_sanbernardo.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(200,"ANTONIO VARAS","/sede/a_varas.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(300,"ALAMEDA","/sede/sede_alameda.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(400,"CAMPUS ARAUCO","/sede/sede_arauco.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(500,"MAIPU","/sede/sede_maipu.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(600,"MELIPILLA","/sede/sede_melipilla.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(700,"PADRE ALONSO DE OVALLE","/sede/sede_padre_alonso.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(800,"PLAZA NORTE","/sede/sede_plazanorte.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(900,"PLAZA OESTE","/sede/sede_plazaoeste.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1000,"PUENTE ALTO","/sede/sede_puentealto.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1100,"SAN ANDRÉS DE CONCEPCIÓN","/sede/sede_sanandres.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1200,"SAN CARLOS DE APOQUINDO","/sede/sede_sancarlos.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1300,"SAN JOAQUIN","/sede/sede_sanjoaquin.jpg",true);
INSERT INTO sede(id,nombre,img,activo) VALUES(1400,"VALPARAISO","/sede/sede_valparaiso.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1500,"PLAZA VESPUCIO","/sede/sede_vespucio.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1600,"VIÑA DEL MAR","/sede/sede_vina.jpg",false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1800,'CAMPUS VILLARICA','/sede/sede_villarica.jpg',false);
INSERT INTO sede(id,nombre,img,activo) VALUES(1900,'CASA CENTRAL','/sede/sede_casa_central.jpg',false);
INSERT INTO sede(id,nombre,img,activo) VALUES(2000,'PUERTO MONTT','/sede/sede_puerto_montt.jpg',false);
INSERT INTO sede(id,nombre,img,activo) VALUES(2100,'EDUCACIÓN CONTINUA','/sede/educacion_continua.jpg',false);
